services:
  - type: web
    name: wyzer-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: "./build"
    envVars:
      - key: REACT_APP_API_URL
        value: https://wyzer-backend.onrender.com
      - key: NODE_VERSION
        value: 18.x
