import {
  ShoppingBagIcon,
  HomeIcon,
  TruckIcon,
  FilmIcon,
  AcademicCapIcon,
  HeartIcon,
  GiftIcon,
  BriefcaseIcon,
  WrenchIcon,
  MusicalNoteIcon,
  ComputerDesktopIcon,
  DevicePhoneMobileIcon,
  BanknotesIcon,
  BuildingOfficeIcon,
  CreditCardIcon,
  GlobeAltIcon,
  ShoppingCartIcon,
  UserGroupIcon,
  WalletIcon,
  ChartPieIcon,
} from '@heroicons/react/24/outline';

export const categoryIcons = {
  ShoppingBagIcon,
  HomeIcon,
  TruckIcon,
  FilmIcon,
  AcademicCapIcon,
  HeartIcon,
  GiftIcon,
  BriefcaseIcon,
  WrenchIcon,
  MusicalNoteIcon,
  ComputerDesktopIcon,
  DevicePhoneMobileIcon,
  BanknotesIcon,
  BuildingOfficeIcon,
  CreditCardIcon,
  GlobeAltIcon,
  ShoppingCartIcon,
  UserGroupIcon,
  WalletIcon,
  ChartPieIcon,
};
